### ISSUE TITLE
Call to a member function query() on null when run php artisan migrate

### ISSUE THREAD

**Issue by nhockool1002** [wpstarter/wpstarter#14]
My Connection 
```
DB_CONNECTION=wpdb
DB_HOST=127.0.0.1
DB_PORT=8889
DB_DATABASE=wpstarter
DB_USERNAME=root
DB_PASSWORD=root
```

I make sure this info can access to my database. But when run `php artisan migrate`  the error `Call to a member function query() - In WpPdo.php line 136:` occur. Please support me.

**Comment by fabarea** [comment]
@nhockool1002 It works for me, I can confirm. 

is your wordpress site running besides `php artisan migrate` ? The plugin is well activated?

If yes, you need to debug how the object "$wpdb" is passed.  

`wp-content/plugins/my-cool-plugin/vendor/wpstarter/framework/src/WpStarter/Wordpress/Database/WpPdo.php`

(assuming you have installed the plugin as documented `composer create-project wpstarter/wpstarter my-cool-plugin`)

```php
public function __construct($wpdb, $dsn, $username, $password, $options)
    {
        parent::__construct($dsn, $username, $password, $options);
        var_dump($wpdb); #<--- try adding this to investigate where the problem lies.
        $this->db = $wpdb;
    }
```

**Comment by as247** [comment]
to use wpdb connection it must be installed as wp plugin
