### ISSUE TITLE
Add more examples of a shortcode dealing with forms

### ISSUE THREAD

**Issue by fabarea** [wpstarter/wpstarter#38]
It would be great to provide a more complete example of how to work with forms, and particularly how to handle routing in the context of a shortcode.

Suppose we have a form that will register a user for a newsletter. The form will have the following fields:

- name
- email

We need to handle the following cases / routing:

- the display of the form (method `GET`)
- the submission of the form. If the data is validated with create a new user (method `POST`) if not, we still display the form so that the user can correct the faulty data.
- after the form data has been saved with success, we display a success to the user along with an empy form.

We would like to handle the form by the mean of a shortcode so that an editor can install it on any page.

How would you implement that with WpStarter?

Would you add a new route in `routes/wp.php` (1) or handle this with a shortcode like in `app/View/Shortcodes/SampleShortcode.php` (2)? The problem with approach "2", will be the routing, AFAIK

I notice the function `post` in `app/Http/Controllers/WelcomeController.php`, but couldn't see how to use it.

If we could possibly extend this starter plugin and add an example, I guess it would be beneficial for other people.

**Comment by as247** [comment]
This quite easy to do:
1. in wp route we add 2 routes:
Route::get('my-form','FormController@show')
Route::post('my-form','FormController@process')
in `show` return a `shortcode_view` with your form in blade view use ws_old for input values and @error directive to display error message like laravell
in `process` just use validaton here, it will redirect back with old input and error if validation not passed

**Comment by as247** [comment]
Sample form added in this pull request https://github.com/wpstarter/wpstarter/pull/41

**Comment by fabarea** [comment]
@as247 👍
