### ISSUE TITLE
Wordpress Theme

### ISSUE THREAD

**Issue by pioneersingh321** [wpstarter/wpstarter#39]
Hy its great framework you have developed .. 
how can we use this as a theme in wordpress ?

**Comment by OmerMaximus** [comment]
To upload the WP Starter theme after downloading it from GitHub, follow these steps:

1. Download the Theme: Visit the GitHub repository where the WP Starter theme is hosted and download the theme files to your computer. You can usually find a "Download" button or an option to download the repository as a ZIP file.

2. Extract the ZIP File: Locate the downloaded ZIP file on your computer and extract its contents using a file extraction tool like WinRAR, 7-Zip, or the built-in file extractor in your operating system. This will create a folder containing the theme files.

3. Connect to your WordPress Website: Log in to your WordPress website using your administrator credentials. The login page is typically located at `yourwebsite.com/wp-admin`.

4. Access the Themes Section: After logging in, you'll be directed to the WordPress Dashboard. In the left-hand menu, navigate to "Appearance" and click on "Themes." This will take you to the Themes section.

5. Upload the Theme: In the Themes section, click on the "Add New" button at the top of the page.

6. Choose the Theme File: On the next page, click on the "Upload Theme" button. Then, click on the "Choose File" button and select the theme folder you extracted from the ZIP file in step 2.

7. Install the Theme: After selecting the theme folder, click on the "Install Now" button. WordPress will now upload and install the WP Starter theme.

8. Activate the Theme: Once the theme installation is complete, click on the "Activate" button to activate the WP Starter theme for your WordPress website.

After following these steps, the WP Starter theme will be uploaded and activated on your WordPress website. You can now customize it and begin building your website using the features and options provided by the theme.

I did this step by step procedure on my client's website for another theme, and the website link was https://www.primehomepicks.com and it worked out perfectly

**Comment by as247** [comment]
Hi @pioneersingh321 This should not used as theme. This should be used as mu-plugins (must use). however if you want to intergrated with theme i sugess following structure:
- wp-admin
- wp-includes
- wp-starter
- wp-content/themes/your-theme/functions.php
in functions.php load wp-starter by call:
`include ABSPATH.'/wp-starter/main.php';`
Of course you may move wp-starter into theme folder but this not recommended
